### ISSUE TITLE
Sir,can you provide the image of the openfaas?

### ISSUE THREAD

**Issue by CS71551** [tjulym/Chiron#1]
I wanted to replicate the experiment, but I couldn't find a mirror for openfaas

**Comment by tjulym** [comment]
Thank you for your comments!

It seems that Openfaas has deleted the mirror version used in the current project, so we need to import a local backup. We have uploaded our local backup and updated the [instruction](https://github.com/tjulym/Chiron/tree/main/Installation).

**Comment by CS71551** [comment]
> Thank you for your comments!
> 
> It seems that Openfaas has deleted the mirror version used in the current project, so we need to import a local backup. We have uploaded our local backup and updated the [instruction](https://github.com/tjulym/Chiron/tree/main/Installation).

Thanks for getting back to me. The gateway is up and running now. On another note, I've run into a similar issue with the queue worker while deploying OpenFaaS.`ghcr.io/openfaas/queue-worker:0.14.1`

Meanwhile, when I deployed MPK warp in another version of openfaas, I could not find the image of `openfaas/of-watchdog:0.7.7 as watchdog`.To solve this problem, I changed 
```
FROM openfaas/of-watchdog:0.7.7 as watchdog

FROM python:3.7-slim-buster

COPY --from=watchdog /fwatchdog /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog
```

to 
```
FROM ghcr.io/openfaas/of-watchdog:0.7.7 as watchdog
FROM python:3.7-slim-buster as build



ADD https://github.com/openfaas/of-watchdog/releases/download/0.7.7/of-watchdog /usr/bin/fwatchdog
RUN chmod +x /usr/bin/fwatchdog 
```
in `Chiron/Evaluation/wraps/template/python3-mpk/Dockerfile. `
At this time, the pod of MPK Wrap ran successfully, but when I ran run_finra5.py to Chiron-M, it appeared
```
Traceback (most recent call last):
  File "run_finra5.py", line 82, in <module>
    get_lats()
  File "run_finra5.py", line 67, in get_lats
    res_j = json.loads(res)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Thank you, Sir, for graciously dedicating your time to address my concern. I eagerly await your response.

**Comment by tjulym** [comment]
Thanks for your feedback!

We have added the our local backup of `ghcr.io/openfaas/queue-worker:0.14.1` & `openfaas/of-watchdog:0.7.7`. Please re-execute `install_imgs.sh`.

As for the execution issue of `Chiron-M`, it works fine in our local cluster. I hope the following suggestions can help you:

1. Please ensure that the `yfinance` function is also deployed.
2. You can add `print(res)` (e..g, at line 67 of  `Evaluation/latency/finra/run_finra5.py`) to print error logs.
3. You can also print the logs of `finra-wrap` pod in the k8s namepace of `openfaas-fn` through `kubectl get pods -n openfaas-fn` and `kubectl logs finra-wrap-replace_it_with_pod_name -n openfaas-fn`. 
4. It is also possible that there is a compatibility issue with MPK, and deleting the function and redeploying it may solve the problem.

**Comment by CS71551** [comment]
> Thanks for your feedback!
> 
> We have added the our local backup of `ghcr.io/openfaas/queue-worker:0.14.1` & `openfaas/of-watchdog:0.7.7`. Please re-execute `install_imgs.sh`.
> 
> As for the execution issue of `Chiron-M`, it works fine in our local cluster. I hope the following suggestions can help you:
> 
> 1. Please ensure that the `yfinance` function is also deployed.
> 2. You can add `print(res)` (e..g, at line 67 of  `Evaluation/latency/finra/run_finra5.py`) to print error logs.
> 3. You can also print the logs of `finra-wrap` pod in the k8s namepace of `openfaas-fn` through `kubectl get pods -n openfaas-fn` and `kubectl logs finra-wrap-replace_it_with_pod_name -n openfaas-fn`.
> 4. It is also possible that there is a compatibility issue with MPK, and deleting the function and redeploying it may solve the problem.

Thank you, Sir. I have successfully deployed the experimental environment. Regarding the previous error with Chiron-M, after my debugging, using `python3... /.. /deploy.py finra-wrap, wraps/Chiron-M.py`, and using the following code 

```
import requests
import threading
import random
import string
import json
import time
import subprocess

from OpenFaaS import workflow_OpenFaaS

url = "http://127.0.0.1:31112/function/finra-wrap"
data = '{"body":{ "portfolioType":"S&P", "portfolio":"1234"}}'
 for i in range(times+1):
                res = requests.post(url, data=data).text
                res_j = json.loads(res)
                lats.append((res_j["time"]["workflow"]["end"] - res_j["time"]["workflow"]["start"])*1000)
avg_lat = sum(lats[1:])/(len(lats)-1)
        print("%s: %f" % (method, avg_lat))
        all_lats.append(avg_lat)
```
the previous error occurs on the first execution, but run it again and the result appears.

Sir, may I inquire if my approach is indeed correct? Once again, I express my gratitude for your patient guidance.

**Comment by tjulym** [comment]
Thanks for your feedback!

I think you have successfully run Chiron-M. We will update the script to catch the possible exception in Chiron-M . Looking forward to your further feedback!

**Comment by CS71551** [comment]
> Thanks for your feedback!
> 
> I think you have successfully run Chiron-M. We will update the script to catch the possible exception in Chiron-M . Looking forward to your further feedback!

Thank you, Sir. I have no further inquiries. I appreciate your patient guidance. 

Wishing you a seamless journey ahead and a path filled with joy.
